/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-07 at 13:47:44 UTC 
 * Modify at your own risk.
 */

package com.johan.vertretungsplan_2.vertretungsplanserializedendpoint.model;

/**
 * Model definition for VertretungsplanSerialized.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the vertretungsplanserializedendpoint. For a detailed
 * explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class VertretungsplanSerialized extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String json;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String schoolId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getJson() {
    return json;
  }

  /**
   * @param json json or {@code null} for none
   */
  public VertretungsplanSerialized setJson(java.lang.String json) {
    this.json = json;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSchoolId() {
    return schoolId;
  }

  /**
   * @param schoolId schoolId or {@code null} for none
   */
  public VertretungsplanSerialized setSchoolId(java.lang.String schoolId) {
    this.schoolId = schoolId;
    return this;
  }

  @Override
  public VertretungsplanSerialized set(String fieldName, Object value) {
    return (VertretungsplanSerialized) super.set(fieldName, value);
  }

  @Override
  public VertretungsplanSerialized clone() {
    return (VertretungsplanSerialized) super.clone();
  }

}
